from math import ceil


ACTIVE_VIEW_SIZE = 6
UNBIASED_PERCENT = 0.2
UNBIASED_NODES = ceil(ACTIVE_VIEW_SIZE * UNBIASED_PERCENT)
PASSIVE_SCAN_LENGTH = ACTIVE_VIEW_SIZE
TTL = 10
ID_LENGTH = 10
ACTIVE_VIEW_MAINTAIN_FREQUENCY = 1
