ACTIVE_VIEW_SIZE = 10
UNBIASED_NODES = 0.2
PASSIVE_SCAN_LENGTH = 4
TTL = 10
ID_LENGTH = 10
ACTIVE_VIEW_MAINTAIN_FREQUENCY = 1

DATA_FIELD_COMMAND = "xbot-command"
DATA_FIELD_TTL = "xbot-ttl"
DATA_FIELD_PRIORITY = "xbot-ttl"
DATA_FIELD_ORIGIN_NODE = "xbot-origin-node"
