language: python

# execute lint and py37 as separate CI processes
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: 3.7
      dist: xenial
      env: TOXENV=lint

# install tox
install:
  - pip install --upgrade pip
  - pip install tox
# command to run tests
script:
  - tox