language: python

# execute lint and py37 as separate CI processes
matrix:
  include:
    - python: 3.7
      dist: bionic
      env: TOXENV=py37
    - python: 3.8
      dist: bionic
      env: TOXENV=py37
    - python: 3.7
      dist: bionic
      env: TOXENV=lint

# install tox
install:
  - pip install --upgrade pip
  - pip install tox
  - pip install codecov
# command to run tests
script:
  - tox

after_script:
  # Upload coverage report to 'Codecov'
  - codecov --token=e2776e79-fc57-44b2-9246-6421a9355853