language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
# command to run tests
script:
  - pytest --cov-report term --cov=swaplink tests/
# Upload coverage report to 'Codecov'
after_script:
  - codecov --token=8fe4817f-071f-4d3a-ad2c-b3b2509b461b